enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  "@keplr-wallet/types@*":
    peerDependenciesMeta:
      starknet:
        optional: true
      bitcoinjs-lib:
        optional: true
  "@keplr-wallet/crypto@*":
    peerDependenciesMeta:
      starknet:
        optional: true
      bitcoinjs-lib:
        optional: true
  "@keplr-wallet/provider-extension@*":
    peerDependenciesMeta:
      starknet:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
