[package]
name = "sxrp_token"
version = "0.2.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", branch = "main" }

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
